linters-settings:
  gocyclo:
    min-complexity: 10
  errcheck:
    check-type-assertions: true

linters:
  enable:
    - govet
    - gocyclo
    - revive
    - errcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        # skip checking cyclomatic complexity in tests
        - gocyclo
  exclude-use-default: false
